name: Remind Slack for old PRs

on: [push]

jobs:
  remind_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check old PRs
        id: check_prs
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | \
          jq '[.[] | select(.created_at < (now | . - (1*24*60*60)) and any(.labels[]; .name == "tests-e2e")) | .html_url]' > old_prs.json
          echo "PRs to notify about:"
          cat old_prs.json
      - name: Send Slack Reminder
        if: steps.check_prs.outputs.old_prs != '[]'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "PRs with label 'tests-e2e' open for more than 1 day: $(echo $(cat old_prs.json) | jq -c .)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
