name: Remind Slack for recent PRs

on: [push]

jobs:
  remind_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check recent PRs
        id: check_prs
        run: |
          start_date=$(date -d "1 day ago" +%Y-%m-%d)
          end_date=$(date +%Y-%m-%d)
          query="type:pr+created:$start_date..$end_date+label:tests-e2e+repo:${{ github.repository }}+state:open"

          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -s "https://api.github.com/search/issues?q=$query" | \
          jq '[.items[] | {"url": .html_url, "title": .title}]' > recent_prs.json

      - name: Construct Slack message
        id: construct_msg
        run: |
          prs_list=""
          while read -r pr; do
            url=$(echo "$pr" | jq -r '.url')
            title=$(echo "$pr" | jq -r '.title')
            prs_list="$prs_list\n$title: $url"
          done < <(jq -c '.[]' recent_prs.json)

          echo "::set-output name=payload::{\"text\": \"PRs with label 'tests-e2e' from the last 24 hours:$prs_list\"}"

      - name: Send Slack Reminder
        if: steps.construct_msg.outputs.payload != '[]'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: ${{ steps.construct_msg.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
