name: Remind Slack for old PRs

on: [push]

jobs:
  remind_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check old PRs
        id: check_prs
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | \
               jq '[.[] | .html_url]' > old_prs.json

      - name: Construct Slack message
        id: construct_msg
        run: |
          prs=$(cat old_prs.json)
          echo "::set-output name=payload::{\"text\": \"PRs open for more than 1 day: $prs\"}"

      - name: Send Slack Reminder
        if: steps.check_prs.outputs.old_prs != '[]'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: ${{ steps.construct_msg.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
