name: Remind Slack for old PRs

on: [push]

jobs:
  remind_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check old PRs
        id: check_prs
        run: |
          date=$(date -d "1 day ago" +%Y-%m-%d)
          query="type:pr+created:<$date+label:tests-e2e+repo:${{ github.repository }}+state:open"

          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -s "https://api.github.com/search/issues?q=$query" | \
          jq '[.items[] | .html_url]' > old_prs.json

      - name: Construct Slack message
        id: construct_msg
        run: |
          prs=$(jq -c . < old_prs.json)
          payload=$(jq -nc --arg prs "$prs" '{"text": ("PRs open for more than 1 day: " + $prs)}')
          echo "::set-output name=payload::$payload"

      - name: Send Slack Reminder
        if: steps.check_prs.outputs.payload != '[]'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: ${{ steps.construct_msg.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
