name: Notify Slack on PR with tests label

on:
  pull_request:
    types:
      - labeled

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'tests-e2e')
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New PR#${{ github.event.pull_request.number }} with 'tests-e2e' label has been created."
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|View PR>"
                  }
                }
              ]

            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
