name: Notify Slack with new PRs containing tests-e2e label

on:
  pull_request:
    types:
      - labeled

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'tests-e2e')
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": 
                  {
                    "type": "mrkdwn",
                    "text": "New PR: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> ready for review"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
